# -*- coding: utf-8 -*-
"""TMS_Pred

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wMSVv4K-dHDp3fCDq_NM7B1onYeV3q8A
"""

import json
import joblib
from azureml.core.model import Model
import pandas as pd
import category_encoders as ce
from tensorflow import keras
from sklearn.preprocessing import MinMaxScaler

def init():
    global encoder, predictor
    model1_path = Model.get_model_path('Store_Sales_Pred_Encoder',)
    model2_path = Model.get_model_path('Store_Sales_Pred_Model')
    encoder = joblib.load(model1_path)
    predictor = keras.models.load_model(model2_path)

def run(raw_data):
    data = json.loads(raw_data)['data']
    data = pd.DataFrame.from_dict(data)
    data_encoded = encoder.transform(data)
    mx = MinMaxScaler()
    data_encoded = mx.fit_transform(data_encoded)
    # data_encoded = data_encoded.to_numpy()
    data_encoded = data_encoded.reshape(1,len(data_encoded),32)
    preds = predictor.predict(data_encoded)
    return json.dumps(preds.tolist())